// Generated by bench2verilog.py
module adder_2_bit(
    A0, A1, B0, B1, Cin, Cout, S0, S1
);

  input  A0, A1, B0, B1, Cin;
  output Cout, S0, S1;
  wire   CONST0, CONST1, n_not_A0, n_not_A1, n_not_B0, n_not_B1, n_not_Cin, p_Cout_0, p_Cout_1, p_Cout_10, p_Cout_11, p_Cout_12, p_Cout_13, p_Cout_14, p_Cout_15, p_Cout_2, p_Cout_3, p_Cout_4, p_Cout_5, p_Cout_6, p_Cout_7, p_Cout_8, p_Cout_9, p_S0_0, p_S0_1, p_S0_10, p_S0_11, p_S0_12, p_S0_13, p_S0_14, p_S0_15, p_S0_2, p_S0_3, p_S0_4, p_S0_5, p_S0_6, p_S0_7, p_S0_8, p_S0_9, p_S1_0, p_S1_1, p_S1_10, p_S1_11, p_S1_12, p_S1_13, p_S1_14, p_S1_15, p_S1_2, p_S1_3, p_S1_4, p_S1_5, p_S1_6, p_S1_7, p_S1_8, p_S1_9;

  assign CONST0 = (A0 & n_not_A0);
  assign CONST1 = (A0 | n_not_A0);
  assign Cout = (p_Cout_0 | p_Cout_1 | p_Cout_2 | p_Cout_3 | p_Cout_4 | p_Cout_5 | p_Cout_6 | p_Cout_7 | p_Cout_8 | p_Cout_9 | p_Cout_10 | p_Cout_11 | p_Cout_12 | p_Cout_13 | p_Cout_14 | p_Cout_15);
  assign S0 = (p_S0_0 | p_S0_1 | p_S0_2 | p_S0_3 | p_S0_4 | p_S0_5 | p_S0_6 | p_S0_7 | p_S0_8 | p_S0_9 | p_S0_10 | p_S0_11 | p_S0_12 | p_S0_13 | p_S0_14 | p_S0_15);
  assign S1 = (p_S1_0 | p_S1_1 | p_S1_2 | p_S1_3 | p_S1_4 | p_S1_5 | p_S1_6 | p_S1_7 | p_S1_8 | p_S1_9 | p_S1_10 | p_S1_11 | p_S1_12 | p_S1_13 | p_S1_14 | p_S1_15);
  assign n_not_A0 = ~(A0);
  assign n_not_A1 = ~(A1);
  assign n_not_B0 = ~(B0);
  assign n_not_B1 = ~(B1);
  assign n_not_Cin = ~(Cin);
  assign p_Cout_0 = (n_not_A0 & n_not_B0 & A1 & B1 & n_not_Cin);
  assign p_Cout_1 = (n_not_A0 & n_not_B0 & A1 & B1 & Cin);
  assign p_Cout_10 = (A0 & B0 & n_not_A1 & B1 & n_not_Cin);
  assign p_Cout_11 = (A0 & B0 & n_not_A1 & B1 & Cin);
  assign p_Cout_12 = (A0 & B0 & A1 & n_not_B1 & n_not_Cin);
  assign p_Cout_13 = (A0 & B0 & A1 & n_not_B1 & Cin);
  assign p_Cout_14 = (A0 & B0 & A1 & B1 & n_not_Cin);
  assign p_Cout_15 = (A0 & B0 & A1 & B1 & Cin);
  assign p_Cout_2 = (n_not_A0 & B0 & n_not_A1 & B1 & Cin);
  assign p_Cout_3 = (n_not_A0 & B0 & A1 & n_not_B1 & Cin);
  assign p_Cout_4 = (n_not_A0 & B0 & A1 & B1 & n_not_Cin);
  assign p_Cout_5 = (n_not_A0 & B0 & A1 & B1 & Cin);
  assign p_Cout_6 = (A0 & n_not_B0 & n_not_A1 & B1 & Cin);
  assign p_Cout_7 = (A0 & n_not_B0 & A1 & n_not_B1 & Cin);
  assign p_Cout_8 = (A0 & n_not_B0 & A1 & B1 & n_not_Cin);
  assign p_Cout_9 = (A0 & n_not_B0 & A1 & B1 & Cin);
  assign p_S0_0 = (n_not_A0 & n_not_B0 & n_not_A1 & n_not_B1 & Cin);
  assign p_S0_1 = (n_not_A0 & n_not_B0 & n_not_A1 & B1 & Cin);
  assign p_S0_10 = (A0 & n_not_B0 & A1 & n_not_B1 & n_not_Cin);
  assign p_S0_11 = (A0 & n_not_B0 & A1 & B1 & n_not_Cin);
  assign p_S0_12 = (A0 & B0 & n_not_A1 & n_not_B1 & Cin);
  assign p_S0_13 = (A0 & B0 & n_not_A1 & B1 & Cin);
  assign p_S0_14 = (A0 & B0 & A1 & n_not_B1 & Cin);
  assign p_S0_15 = (A0 & B0 & A1 & B1 & Cin);
  assign p_S0_2 = (n_not_A0 & n_not_B0 & A1 & n_not_B1 & Cin);
  assign p_S0_3 = (n_not_A0 & n_not_B0 & A1 & B1 & Cin);
  assign p_S0_4 = (n_not_A0 & B0 & n_not_A1 & n_not_B1 & n_not_Cin);
  assign p_S0_5 = (n_not_A0 & B0 & n_not_A1 & B1 & n_not_Cin);
  assign p_S0_6 = (n_not_A0 & B0 & A1 & n_not_B1 & n_not_Cin);
  assign p_S0_7 = (n_not_A0 & B0 & A1 & B1 & n_not_Cin);
  assign p_S0_8 = (A0 & n_not_B0 & n_not_A1 & n_not_B1 & n_not_Cin);
  assign p_S0_9 = (A0 & n_not_B0 & n_not_A1 & B1 & n_not_Cin);
  assign p_S1_0 = (n_not_A0 & n_not_B0 & n_not_A1 & B1 & n_not_Cin);
  assign p_S1_1 = (n_not_A0 & n_not_B0 & n_not_A1 & B1 & Cin);
  assign p_S1_10 = (A0 & n_not_B0 & A1 & n_not_B1 & n_not_Cin);
  assign p_S1_11 = (A0 & n_not_B0 & A1 & B1 & Cin);
  assign p_S1_12 = (A0 & B0 & n_not_A1 & n_not_B1 & n_not_Cin);
  assign p_S1_13 = (A0 & B0 & n_not_A1 & n_not_B1 & Cin);
  assign p_S1_14 = (A0 & B0 & A1 & B1 & n_not_Cin);
  assign p_S1_15 = (A0 & B0 & A1 & B1 & Cin);
  assign p_S1_2 = (n_not_A0 & n_not_B0 & A1 & n_not_B1 & n_not_Cin);
  assign p_S1_3 = (n_not_A0 & n_not_B0 & A1 & n_not_B1 & Cin);
  assign p_S1_4 = (n_not_A0 & B0 & n_not_A1 & n_not_B1 & Cin);
  assign p_S1_5 = (n_not_A0 & B0 & n_not_A1 & B1 & n_not_Cin);
  assign p_S1_6 = (n_not_A0 & B0 & A1 & n_not_B1 & n_not_Cin);
  assign p_S1_7 = (n_not_A0 & B0 & A1 & B1 & Cin);
  assign p_S1_8 = (A0 & n_not_B0 & n_not_A1 & n_not_B1 & Cin);
  assign p_S1_9 = (A0 & n_not_B0 & n_not_A1 & B1 & n_not_Cin);

endmodule
